# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5ebaeebfa6cee1e7536b977b814b91c7e99f5694fcaa035dd2c30531a70069f3fa928b7eda0889b16fac36f3bd2341f3d337b66774955e18f7873654bc728d2

test:
  secret_key_base: 149c2ea73193e821210657fe195196210de7b6f12de24d1961f9d9faa64c33d9876a238b923fb01d04914f8476f0abdbc31c5a378592f6c4e21bc80306180672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
